### ISSUE TITLE
Only affect the first occurrence of an alignment char in a line

### ISSUE THREAD

**Issue by martin-wiseweb** [annsk/vscode-alignment#7]
When aligning lines such as the following with `spaceBefore` and `spaceAfter` set:

```javascript
var something = 1;
var b = ( something === 1 ? true : false);
```

You would expect only the `=` after `something` and `b` to be aligned. But also, spaces may get added to _all_ `=` on a line, like so:

```javascript
var something = 1;
var b = ( something = = = 1 ? true : false);
```

**Comment by annsk** [comment]
Corrected by extension default configuration. Also I added Align to first char commend. 

Resolved in v0.3.0
